wrap = "keep"         # options: {"keep", "no", INTEGER}
number = true        # options: {false, true}
end_of_line = "lf"    # options: {"lf", "crlf", "keep"}
validate = true       # options: {false, true}
extensions = [      # options: a list of enabled extensions (default: all installed are enabled)
     "gfm",
]
# codeformatters = [  # options: a list of enabled code formatter languages (default: all installed are enabled)
#     "python",
#     "json",
# ]
