repos:
- repo: https://github.com/hukkin/mdformat
  rev: 1.0.0  # Use the ref you want to point at
  hooks:
  - id: mdformat
    # Optionally add plugins
    additional_dependencies:
    - mdformat-gfm
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: ''  # Use the sha / tag you want to point at
  hooks:
  - id: clang-format
- repo: 'https://github.com/PyCQA/autoflake'
  rev: v2.3.1
  hooks:
    - id: autoflake
- repo: 'https://github.com/PyCQA/isort'
  rev: 6.0.1
  hooks:
    - id: isort
- repo: 'https://github.com/psf/black-pre-commit-mirror'
  rev: 25.9.0
  hooks:
    - id: black
