[project]
name = "mind"
version = "0.0.0"
description = "Default template for PDM package"
authors = [
    {name = "RenChu Wang", email = "patrick1031wang@gmail.com"},
]
dependencies = ["pre-commit>=4.5.1"]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
